name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID=Ov23liHZ7CNmc4IIo0f7
GITHUB_OWNER=xn2xx
GITHUB_REPO=NavSphere
GITHUB_BRANCH=main
NEXTAUTH_URL=https://nav.scitqn.top/api/auth
NEXT_PUBLIC_API_URL=https://nav.scitqn.top
